export enum muscleGroups {
  CHEST = "Chest",
  LEG = "Leg",
  BACK = "Back",
  ABS = "Abs",
  CAVLE = "Cavle",
  GLUTE = "Glute",
  BICEP = "Bicep",
  TRICEP = "Tricep",
  SHOULDER = "Shoulder",
  TRAP = "Traps",
  LATS = "Lats",
  FOREARM = "Forarms",
  NECK = "Neck",
  ADDUCTOR = "Adductors",
  THIGH = "Thighs",
  HAMSTRING = "Hamstring",
  NONE = "N/A",
}
